### ISSUE TITLE
Ascii issue

### ISSUE THREAD

**Issue by halali** [l3uddz/plex_patrol#1]
Hello

i have issue

```
2017-08-11 13:05:35,736 - ERROR      - plex_patrol.utils.plex -  get_streams              - Exception retrieving streams
 from request_url='http://localhost:32400/status/sessions', token='xxxxxx':
Traceback (most recent call last):
  File "D:\apps\plex_patrol\utils\plex.py", line 77, in get_streams
    streams.append(PlexStream(stream))
  File "D:\apps\plex_patrol\utils\plex.py", line 156, in __init__
    self.title = "{} {}x{}".format(stream['grandparentTitle'], stream['parentIndex'], stream['index'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
```
this probably happend becouse i have titles in slovak Language "Prolhané krásky - 6. epizoda"
any solution how to fix it ?

**Comment by l3uddz** [comment]
yeah this is a bug i did not anticipate. i will fix it and reply here for u to test when i have a moment

**Comment by l3uddz** [comment]
pls let me know if this problem is fixed for you.

**Comment by halali** [comment]
Now it works.

Thx.

**Comment by l3uddz** [comment]
Great 👍

**Comment by halali** [comment]
And maybe if you have time you can add new future.

Somethink like this.
https://gist.github.com/blacktwin/6d08b94ca3e80d3ed0bb3c7172fae21d

**Comment by l3uddz** [comment]
done. it will only allow 1 stream to remain, so if user X streams 5 times from 5 IPs, 4 streams will be kicked and 1 will remain.

**Comment by halali** [comment]
Thx this is awsome
