### ISSUE TITLE
ImportError: No module named 'decouple'

### ISSUE THREAD

**Issue by reaperofpower** [l3uddz/plex_patrol#13]
Any idea what is causing this? I created a new config and still nothing

```
agentk@stargate:~/scripts/plex_patrol$ sudo ./patrol.py
Traceback (most recent call last):
  File "./patrol.py", line 5, in <module>
    from utils import config
  File "/home/scripts/plex_patrol/utils/config.py", line 3, in <module>
    from decouple import AutoConfig, Csv
ImportError: No module named 'decouple'
```

```

agentk@stargate:~/scripts/plex_patrol$ pip install python-decouple
Requirement already satisfied: python-decouple in /usr/local/lib/python2.7/dist-packages (3.1)

```

**Comment by davidheidar** [comment]
Getting the same error when running this script, did you mange to fix?

**Comment by l3uddz** [comment]
This is likely due to the decouple module not being installed. Or it being installed for the wrong interpreter. 

Try using the which python command to find the binary, then you should be able todo 

/usr/bin/python -m pip install -r requirements.txt

**Comment by davidheidar** [comment]
Output from command: **/usr/bin/python -m pip install -r requirements.txt**:

Requirement already satisfied: requests~=2.18.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (2.18.4)
Requirement already satisfied: python-decouple==3.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (3.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests~=2.18.4->-r requirements.txt (line 1)) (2018.1.18)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests~=2.18.4->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests~=2.18.4->-r requirements.txt (line 1)) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests~=2.18.4->-r requirements.txt (line 1)) (1.22)

**Comment by reaperofpower** [comment]
Mine looks the same as yours @davidheidar what did you do to fix it? I tried running it from /use/bin/python2.7 and no luck :(

**Comment by elielam** [comment]
I have the same error and @l3uddz command don't resolve it for me.

```
sudo -H /usr/bin/python -m pip install -r requirements.txt

Requirement already satisfied: requests~=2.18.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-decouple==3.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests~=2.18.4->-r requirements.txt (line 1))
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests~=2.18.4->-r requirements.txt (line 1))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests~=2.18.4->-r requirements.txt (line 1))
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/dist-packages (from requests~=2.18.4->-r requirements.txt (line 1))
```

```
 sudo ./patrol.py

Traceback (most recent call last):
  File "./patrol.py", line 5, in <module>
    from utils import config
  File "/opt/plex_patrol/utils/config.py", line 3, in <module>
    from decouple import AutoConfig, Csv
ModuleNotFoundError: No module named 'decouple'
```

```
sudo python patrol.py

Traceback (most recent call last):
  File "patrol.py", line 7, in <module>
    from utils.plex import Plex
  File "/opt/plex_patrol/utils/plex.py", line 3, in <module>
    from urllib.parse import urljoin
ImportError: No module named parse
```

If u can say us how you had fix that 🙏

**Comment by JOFLIX** [comment]
I had the same error and this helped: **pip install python_decouple**
I hope this will work too for you bros!

**Comment by allprod** [comment]
This issue is still active. I'm on Ubuntu 18.04 and python-decouple is installed on both the venv and default python for the Operating system but still the error persists. before I started sing decouple the site ran, after I started using it the server keeps on crying about it not being found and I find that to be extremely odd and annoying.

I do not understand how this bug works, I tried to use the venve and it comes up, I switch to using the default environment and it still creeps up. what do I do to get rid of it?

**Comment by steve-barnard** [comment]
Appears this issue still persists.
`pip install python_decouple
Requirement already satisfied: python_decouple in ./.venv/lib/python3.7/site-packages (3.8)`

` File "./main.py", line 9, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'`
