### ISSUE TITLE
Kicking not working

### ISSUE THREAD

**Issue by irodimus** [l3uddz/plex_patrol#4]
I'm on PMS 1.11.1.4730 and have just noticed that plex_patrol is not longer kicking paused streams. I have it setup to kick paused streams at 15 min and when they time comes, it will say the stream was killed but nothing will happen on the client. The status.log updates that the stream is still paused but this time without a "type" or "Session key", just showing unknown. The clients this occurred on was on Plex Web and on a Roku.

**Comment by After-Shock** [comment]
I'm on the same version as well but I don't think this is a plex_patrol issue as I can no longer kick streams from Tautulli or Plex either.

**Comment by irodimus** [comment]
Just wanted to say that getting a new Plex Token may have resolved it.
